Repository ahmetYilmaz88/group-2-project, pull requests merged in 2021-08, with the labels that each got.

#9 Ateeq branch added
  src/Ateeq.java
Labels: good first issue

#15 second branch added
  src/Ateeq/Ateeq.java
  src/Ateeq/Class2_SecondBranch.java
Labels: bug

#28 i did a work and its done by me (samir) plz check and approve that
  src/b23user/TC100.java
Labels: documentation

#33 creating a pull request by inteliji
  src/Ateeq/LogoutFunction.java
Labels: help wanted
